name:                 mlf2
version:              0.2.0.0
visibility:           public
id:                   mlf2-0.2.0.0-inplace
key:                  mlf2-0.2.0.0-inplace
license:              BSD-3-Clause
maintainer:           patrickwalesss@gmail.com
author:               soulomoon
abi:                  inplace
exposed:              True
exposed-modules:      MLF.API MLF.Pipeline MLF.XMLF
import-dirs:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/build

library-dirs:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/build

library-dirs-static:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/build

dynamic-library-dirs:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/build

data-dir:             /Users/ares/.codex/worktrees/d432/mlf4/.
hs-libraries:         HSmlf2-0.2.0.0-inplace
depends:
    base-4.21.0.0-958c containers-0.7-f896
    mlf2-0.2.0.0-inplace-mlf2-internal mtl-2.3.1-b11b

haddock-interfaces:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/doc/html/mlf2/mlf2.haddock

haddock-html:
    /Users/ares/.codex/worktrees/d432/mlf4/dist-newstyle-round129-p5-serial/build/aarch64-osx/ghc-9.12.2/mlf2-0.2.0.0/doc/html/mlf2
