//! mlfp_io — Rust runtime helpers for mlfp IO primitives.
//!
//! These functions are declared as external in the LLVM IR generated by the
//! mlfp backend and linked at native-executable build time.

use std::env;
use std::ffi::{CStr, CString};
use std::fs;
use std::io::{self, BufRead, Write};
use std::os::raw::c_char;
use std::ptr;

/// Read a line from stdin into a heap-allocated null-terminated string.
///
/// Returns a C string (without the trailing newline).
/// Returns null on EOF before any characters were read.
/// The caller is responsible for freeing the returned pointer with `mlfp_runtime_free`.
#[no_mangle]
pub extern "C" fn mlfp_runtime_read_line() -> *mut c_char {
    let stdin = io::stdin();
    let mut line = String::new();
    match stdin.lock().read_line(&mut line) {
        Ok(0) => ptr::null_mut(), // EOF
        Ok(_) => {
            // Remove trailing newline if present
            if line.ends_with('\n') {
                line.pop();
                if line.ends_with('\r') {
                    line.pop();
                }
            }
            match CString::new(line) {
                Ok(c_str) => c_str.into_raw(),
                Err(_) => ptr::null_mut(),
            }
        }
        Err(_) => ptr::null_mut(),
    }
}

/// Read an entire file into a heap-allocated null-terminated string.
///
/// Returns null if the file cannot be opened or read.
/// The caller is responsible for freeing the returned pointer with `mlfp_runtime_free`.
#[no_mangle]
pub extern "C" fn mlfp_runtime_read_file(path: *const c_char) -> *mut c_char {
    if path.is_null() {
        return ptr::null_mut();
    }
    let path_str = match unsafe { CStr::from_ptr(path) }.to_str() {
        Ok(s) => s,
        Err(_) => return ptr::null_mut(),
    };
    match fs::read_to_string(path_str) {
        Ok(contents) => match CString::new(contents) {
            Ok(c_str) => c_str.into_raw(),
            Err(_) => ptr::null_mut(),
        },
        Err(_) => ptr::null_mut(),
    }
}

/// Write a string to a file, creating or truncating it.
///
/// Returns 0 on success, -1 on failure.
#[no_mangle]
pub extern "C" fn mlfp_runtime_write_file(
    path: *const c_char,
    contents: *const c_char,
) -> i32 {
    let path_str = match unsafe { CStr::from_ptr(path) }.to_str() {
        Ok(s) => s,
        Err(_) => return -1,
    };
    let contents_str = match unsafe { CStr::from_ptr(contents) }.to_str() {
        Ok(s) => s,
        Err(_) => return -1,
    };
    match fs::write(path_str, contents_str) {
        Ok(()) => 0,
        Err(_) => -1,
    }
}

/// Append a string to a file, creating it if it doesn't exist.
///
/// Returns 0 on success, -1 on failure.
#[no_mangle]
pub extern "C" fn mlfp_runtime_append_file(
    path: *const c_char,
    contents: *const c_char,
) -> i32 {
    let path_str = match unsafe { CStr::from_ptr(path) }.to_str() {
        Ok(s) => s,
        Err(_) => return -1,
    };
    let contents_str = match unsafe { CStr::from_ptr(contents) }.to_str() {
        Ok(s) => s,
        Err(_) => return -1,
    };
    match fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path_str)
    {
        Ok(mut file) => match file.write_all(contents_str.as_bytes()) {
            Ok(()) => 0,
            Err(_) => -1,
        },
        Err(_) => -1,
    }
}

/// Get command-line arguments as a null-terminated array of C strings.
///
/// Returns a pointer to a null-terminated array of `*mut c_char`.
/// Each string and the array itself are heap-allocated.
/// The caller must free the array with `mlfp_runtime_free_args`.
#[no_mangle]
pub extern "C" fn mlfp_runtime_get_args() -> *mut *mut c_char {
    let args: Vec<CString> = env::args()
        .filter_map(|a| CString::new(a).ok())
        .collect();
    let mut ptrs: Vec<*mut c_char> = args.into_iter().map(|s| s.into_raw()).collect();
    ptrs.push(ptr::null_mut()); // null terminator
    let boxed = ptrs.into_boxed_slice();
    Box::into_raw(boxed) as *mut *mut c_char
}

/// Free the array returned by `mlfp_runtime_get_args`.
///
/// Safety: The pointer must have been returned by `mlfp_runtime_get_args`.
#[no_mangle]
pub unsafe extern "C" fn mlfp_runtime_free_args(ptr: *mut *mut c_char) -> i32 {
    if ptr.is_null() {
        return 0;
    }
    unsafe {
        // Find the null terminator to determine the length
        let mut len = 0;
        while !(*ptr.add(len)).is_null() {
            len += 1;
        }
        // Free each string
        for i in 0..len {
            let s = *ptr.add(i);
            if !s.is_null() {
                drop(CString::from_raw(s));
            }
        }
        // Free the array itself
        let slice = std::slice::from_raw_parts_mut(ptr, len + 1);
        let boxed = Box::from_raw(slice as *mut [*mut c_char]);
        drop(boxed);
    }
    0
}

/// Exit the process with the given status code.
///
/// Never returns.
#[no_mangle]
pub extern "C" fn mlfp_runtime_exit(status: i64) -> ! {
    std::process::exit(status as i32)
}

/// Free a string previously returned by an mlfp_runtime function.
///
/// Safety: The pointer must have been returned by `mlfp_runtime_read_line`,
/// `mlfp_runtime_read_file`, or another function that allocates via CString.
#[no_mangle]
pub unsafe extern "C" fn mlfp_runtime_free(ptr: *mut c_char) {
    if !ptr.is_null() {
        unsafe {
            drop(CString::from_raw(ptr));
        }
    }
}
