#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: bench/ghc-reference/generate-parser-shape.sh [--defs N] [--output PATH] [--module NAME]

Generate a synthetic Haskell module with many parser-shaped top-level
definitions for the GHC per-definition scale reference.

Defaults:
  --defs 914
  --output bench/ghc-reference/ParserShape914.hs
  --module ParserShape914
USAGE
}

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/../.." && pwd)"

defs=914
output_path="$repo_root/bench/ghc-reference/ParserShape914.hs"
module_name="ParserShape914"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --defs)
      [[ $# -ge 2 ]] || { echo "missing value for --defs" >&2; exit 2; }
      defs="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "missing value for --output" >&2; exit 2; }
      output_path="$2"
      shift 2
      ;;
    --module)
      [[ $# -ge 2 ]] || { echo "missing value for --module" >&2; exit 2; }
      module_name="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$defs" in
  ''|*[!0-9]*)
    echo "--defs must be a positive integer" >&2
    exit 2
    ;;
esac

if (( defs < 1 )); then
  echo "--defs must be at least 1" >&2
  exit 2
fi

case "$module_name" in
  ''|*[!A-Za-z0-9_]*|[!A-Z]*)
    echo "--module must be a valid simple Haskell module name" >&2
    exit 2
    ;;
esac

if [[ "$output_path" != /* ]]; then
  output_path="$repo_root/$output_path"
fi

mkdir -p "$(dirname -- "$output_path")"

{
  cat <<EOF
{-# OPTIONS_GHC -Wall #-}
-- Generated by bench/ghc-reference/generate-parser-shape.sh.
module $module_name where

newtype Parser a = Parser { runParser :: String -> Maybe (a, String) }

pureP :: a -> Parser a
pureP value =
    Parser (\input -> Just (value, input))

bindP :: Parser a -> (a -> Parser b) -> Parser b
bindP parser next =
    Parser \$ \input ->
        case runParser parser input of
            Nothing -> Nothing
            Just (value, rest) -> runParser (next value) rest

altP :: Parser a -> Parser a -> Parser a
altP left right =
    Parser \$ \input ->
        case runParser left input of
            Nothing -> runParser right input
            success -> success

tokenP :: Char -> Parser Char
tokenP expected =
    Parser \$ \input ->
        case input of
            c:rest | c == expected -> Just (c, rest)
            _ -> Nothing

mapP :: (a -> b) -> Parser a -> Parser b
mapP f parser =
    bindP parser (pureP . f)

EOF

  for (( i = 1; i <= defs; i++ )); do
    name="$(printf 'p%04d' "$i")"
    char_code=$((97 + ((i - 1) % 26)))
    char="$(printf "\\$(printf '%03o' "$char_code")")"

    printf '%s :: Parser Int\n' "$name"
    if (( i == 1 )); then
      printf "%s =\n" "$name"
      printf "    mapP (\\c -> fromEnum c + %d) (tokenP '%s')\n\n" "$i" "$char"
    else
      prev="$(printf 'p%04d' "$((i - 1))")"
      printf "%s =\n" "$name"
      printf "    bindP %s $ \\\\x ->\n" "$prev"
      printf "        altP\n"
      printf "            (pureP (x + %d))\n" "$i"
      printf "            (mapP (\\c -> x + fromEnum c + %d) (tokenP '%s'))\n\n" "$i" "$char"
    fi
  done

  cat <<'EOF'
allParsers :: [Parser Int]
allParsers =
EOF

  for (( i = 1; i <= defs; i++ )); do
    name="$(printf 'p%04d' "$i")"
    if (( i == 1 )); then
      printf '    [ %s\n' "$name"
    else
      printf '    , %s\n' "$name"
    fi
  done
  printf '    ]\n'
} > "$output_path"

printf 'generated %s (%s defs)\n' "$output_path" "$defs"
