#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: bench/generate-many-defs-comparison.sh [--defs N]
                                               [--mlfp-dir PATH]
                                               [--haskell-source PATH]
                                               [--haskell-module NAME]

Generate matched .mlfp and Haskell modules with many mixed top-level
definitions. The generated shape cycles through aliases, local polymorphic lets,
global polymorphic instantiation, higher-order function arguments, ADT
construction, and case analysis:

  value0001 = 1
  value0002 = value0001
  value0003 = let id = λx x in id value0002
  value0004 = idPoly value0003
  value0005 = useInt (λ(x : Int) value0004)
  value0006 = case Succ Zero of { ... }
  value0007 = case Box value0006 of { ... }
  ...
  main      = valueNNNN

Defaults:
  --defs 1000
  --mlfp-dir bench/benchmarks/many-defs-1000
  --haskell-source bench/ghc-reference/ManyDefs1000.hs
  --haskell-module ManyDefs1000
USAGE
}

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/.." && pwd)"

defs=1000
mlfp_dir=""
haskell_source=""
haskell_module=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --defs)
      [[ $# -ge 2 ]] || { echo "missing value for --defs" >&2; exit 2; }
      defs="$2"
      shift 2
      ;;
    --mlfp-dir)
      [[ $# -ge 2 ]] || { echo "missing value for --mlfp-dir" >&2; exit 2; }
      mlfp_dir="$2"
      shift 2
      ;;
    --haskell-source)
      [[ $# -ge 2 ]] || { echo "missing value for --haskell-source" >&2; exit 2; }
      haskell_source="$2"
      shift 2
      ;;
    --haskell-module)
      [[ $# -ge 2 ]] || { echo "missing value for --haskell-module" >&2; exit 2; }
      haskell_module="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$defs" in
  ''|*[!0-9]*)
    echo "--defs must be a positive integer" >&2
    exit 2
    ;;
esac

if (( defs < 1 )); then
  echo "--defs must be at least 1" >&2
  exit 2
fi

if [[ -z "$mlfp_dir" ]]; then
  mlfp_dir="$repo_root/bench/benchmarks/many-defs-$defs"
elif [[ "$mlfp_dir" != /* ]]; then
  mlfp_dir="$repo_root/$mlfp_dir"
fi

if [[ -z "$haskell_module" ]]; then
  haskell_module="ManyDefs$defs"
fi

case "$haskell_module" in
  ''|*[!A-Za-z0-9_]*|[!A-Z]*)
    echo "--haskell-module must be a valid simple Haskell module name" >&2
    exit 2
    ;;
esac

if [[ -z "$haskell_source" ]]; then
  haskell_source="$repo_root/bench/ghc-reference/$haskell_module.hs"
elif [[ "$haskell_source" != /* ]]; then
  haskell_source="$repo_root/$haskell_source"
fi

mkdir -p "$mlfp_dir" "$(dirname -- "$haskell_source")"

mlfp_file="$mlfp_dir/Main.mlfp"

{
  cat <<'EOF'
module Main export (main) {
  data Nat =
      Zero : Nat
    | Succ : Nat -> Nat;

  data Box =
      Box : Int -> Box;

  def idPoly : ∀ a. a -> a = λx x;

  def useInt : (Int -> Int) -> Int =
    λ(f : Int -> Int) f 1;

EOF

  for (( i = 1; i <= defs; i++ )); do
    name="$(printf 'value%04d' "$i")"
    if (( i == 1 )); then
      printf '  def %s : Int = 1;\n' "$name"
    else
      prev="$(printf 'value%04d' "$((i - 1))")"
      case $(( (i - 2) % 6 )) in
        0)
          printf '  def %s : Int = %s;\n' "$name" "$prev"
          ;;
        1)
          printf '  def %s : Int = let id = λx x in id %s;\n' "$name" "$prev"
          ;;
        2)
          printf '  def %s : Int = idPoly %s;\n' "$name" "$prev"
          ;;
        3)
          printf '  def %s : Int = useInt (λ(x : Int) %s);\n' "$name" "$prev"
          ;;
        4)
          printf '  def %s : Int = case Succ Zero of {\n' "$name"
          printf '    Zero -> %s;\n' "$prev"
          printf '    Succ _ -> %s\n' "$prev"
          printf '  };\n'
          ;;
        *)
          printf '  def %s : Int = case Box %s of {\n' "$name" "$prev"
          printf '    Box x -> x\n'
          printf '  };\n'
          ;;
      esac
    fi
  done

  last="$(printf 'value%04d' "$defs")"
  printf '\n  def main : Int = %s;\n' "$last"
  printf '}\n'
} > "$mlfp_file"

{
  cat <<EOF
{-# OPTIONS_GHC -Wall #-}
-- Generated by bench/generate-many-defs-comparison.sh.
module $haskell_module where

data Nat
    = Zero
    | Succ Nat

data Box
    = Box Int

idPoly :: a -> a
idPoly x =
    x

useInt :: (Int -> Int) -> Int
useInt f =
    f 1

EOF

  for (( i = 1; i <= defs; i++ )); do
    name="$(printf 'value%04d' "$i")"
    printf '%s :: Int\n' "$name"
    if (( i == 1 )); then
      printf '%s = 1\n\n' "$name"
    else
      prev="$(printf 'value%04d' "$((i - 1))")"
      case $(( (i - 2) % 6 )) in
        0)
          printf '%s = %s\n\n' "$name" "$prev"
          ;;
        1)
          printf '%s =\n' "$name"
          printf '    let localId x = x\n'
          printf '     in localId %s\n\n' "$prev"
          ;;
        2)
          printf '%s = idPoly %s\n\n' "$name" "$prev"
          ;;
        3)
          printf '%s = useInt (\\_x -> %s)\n\n' "$name" "$prev"
          ;;
        4)
          printf '%s =\n' "$name"
          printf '    case Succ Zero of\n'
          printf '        Zero -> %s\n' "$prev"
          printf '        Succ _ -> %s\n\n' "$prev"
          ;;
        *)
          printf '%s =\n' "$name"
          printf '    case Box %s of\n' "$prev"
          printf '        Box x -> x\n\n'
          ;;
      esac
    fi
  done

  last="$(printf 'value%04d' "$defs")"
  printf 'mainValue :: Int\n'
  printf 'mainValue = %s\n' "$last"
} > "$haskell_source"

printf 'generated %s (%s value defs plus helpers and main)\n' "${mlfp_file#$repo_root/}" "$defs"
printf 'generated %s (%s value defs plus helpers and mainValue)\n' "${haskell_source#$repo_root/}" "$defs"
