{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE StandaloneKindSignatures #-}
{- |
Module      : MLF.Constraint.Types.Phase
Description : Pipeline phase tracking at the type level
Copyright   : (c) 2024
License     : BSD-3-Clause

This module defines the 'Phase' kind used to index the 'Constraint' type by
pipeline stage. Each phase has a singleton type generated by @singletons-th@
that enables runtime dispatch on the phase value.

The phase progression is:

> Raw → Normalized → Acyclic → Presolved → Solved

See "MLF.Constraint.Types.Graph" for the phase-indexed 'Constraint' type.
-}
module MLF.Constraint.Types.Phase (
    Phase (..),
    SPhase,
    Next,
) where

import Data.Kind (Type)
import Data.Singletons.TH (genSingletons)

-- | Pipeline phases for the constraint graph.
--
-- Each phase represents a distinct processing stage. The 'Constraint' type
-- is indexed by its phase, enforcing at compile time that fields are accessed
-- only when they exist.
data Phase = Raw | Normalized | Acyclic | Presolved | Solved
    deriving (Eq, Show)

genSingletons [''Phase]

-- | Type-level successor for pipeline phases.
type family Next (p :: Phase) :: Phase where
    Next 'Raw        = 'Normalized
    Next 'Normalized = 'Acyclic
    Next 'Acyclic    = 'Presolved
    Next 'Presolved  = 'Solved
    Next 'Solved     = 'Solved
